spring.application.name=allride-ai-service
server.port=8081

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${AI_DB_URL}
spring.datasource.username=${AI_DB_USER}
spring.datasource.password=${AI_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI — OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.embedding.options.model=text-embedding-3-small
PGvector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536

# Spring AI — Ollama (local, free)
#spring.ai.ollama.base-url=http://localhost:11434
## Auto-pull models on first startup if missing
#spring.ai.ollama.init.pull-model-strategy=when_missing
#spring.ai.ollama.init.timeout=10m
#spring.ai.ollama.chat.options.model=llama3.2
#spring.ai.ollama.chat.options.temperature=0.2
#spring.ai.ollama.embedding.options.model=nomic-embed-text
#
## IMPORTANT: nomic-embed-text = 768 dimensions (not 1536)
#spring.ai.vectorstore.pgvector.dimensions=768

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=900000

allride.backend.base-url=${ALLRIDE_BACKEND_URL:http://localhost:8080}
allride.backend.service-key=${AI_SERVICE_INTERNAL_KEY}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

spring.security.user.name=${MY_ENV_USERNAME}
spring.security.user.password=${MY_ENV_PASSWORD}

#logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security=TRACE