export const BOOKING_STEPS = {
  IDLE: "IDLE",

  SELECTING_RIDE: "SELECTING_RIDE",

  CONFIRMING_RIDE: "CONFIRMING_RIDE",

  SEARCHING_DRIVER: "SEARCHING_DRIVER",

  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",

  DRIVER_ARRIVING: "DRIVER_ARRIVING",

  RIDE_STARTED: "RIDE_STARTED",

  RIDE_COMPLETED: "RIDE_COMPLETED",

  RIDE_CANCELLED: "RIDE_CANCELLED",
};
