package com.example.allride.common.constants;

public enum ErrorCode {
    USER_NOT_FOUND,
    DRIVER_UNAVAILABLE,
    DRIVER_PROFILE_NOT_FOUND,
    DRIVER_PROFILE_ALREADY_EXISTS,
    DRIVER_NOT_APPROVED,
    DRIVER_OFFLINE,
    INVALID_TOKEN,
    PAYMENT_FAILED,
    AUTH_INVALID_CREDENTIALS,
    AUTH_INVALID_TOKEN,
    AUTH_UNAUTHORIZED,
    EMAIL_ALREADY_EXISTS,
    RIDE_NOT_FOUND,
    RIDE_NOT_AUTHORIZED,
    RIDE_INVALID_STATE,
    RIDE_ALREADY_ACCEPTED,
    RIDE_ALREADY_CANCELLED,
    INTERNAL_SERVER_ERROR
}
