export const RIDE_STATUS = {
  IDLE: "IDLE",
  SEARCHING_DRIVER: "SEARCHING_DRIVER",
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  DRIVER_ARRIVING: "DRIVER_ARRIVING",
  DRIVER_ARRIVED: "DRIVER_ARRIVED",
  RIDE_STARTED: "RIDE_STARTED",
  RIDE_COMPLETED: "RIDE_COMPLETED",
  RIDE_CANCELLED: "RIDE_CANCELLED",
};
