name: Backend CI

on:
    push:
        branches:
            - dev
        paths:
            - "backend/allride-backend/**"

    pull_request:
        branches:
            - dev
        paths:
            - "backend/allride-backend/**"

env:
    JAVA_VERSION: "21"
    IMAGE_NAME: allride-backend

jobs:
    build-test-scan:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend/allride-backend

        steps:
            #################################################
            # Checkout
            #################################################

            - name: Checkout Code
              uses: actions/checkout@v4

            #################################################
            # Java Setup
            #################################################

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: ${{ env.JAVA_VERSION }}
                  cache: maven

            #################################################
            # Build + Unit Test
            #################################################

            - name: Build and Unit Test
              run: |
                  mvn clean verify
